In [365]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [367]:
df=pd.read_csv("train.csv")
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V45,V47,V50,V51,V52,V59,V63,V72,V75,class
0,0.0,1.0,243.0,29,4528.0,138.0,3.0,29,201.0,0.0,...,2,3,71.0,0,0,46.0,1,2,0,1
1,0.0,20.0,8.0,14,4183.0,183.0,4.0,26,156.0,0.0,...,5,7,20.0,0,2,13.0,9,6,0,1
2,14.0,2.0,2.0,9,1113.0,15.0,37.0,31,78.0,1.0,...,7,5,11.0,0,0,7.0,9,2,1,0
3,0.0,175.0,17.0,16,4250.0,68.0,8.0,30,152.0,0.0,...,1,3,0.0,1,1,31.0,6,4,5,1
4,2.0,-1.0,1.0,3,0.0,0.0,2.0,5,6.0,1.0,...,1,5,0.0,0,0,2.0,8,0,1,1

In [368]:
df.shape

(40776, 32)

In [371]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40776 entries, 0 to 40775
Data columns (total 32 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      40776 non-null  float64
 1   V2      40776 non-null  float64
 2   V3      40776 non-null  float64
 3   V4      40776 non-null  int64
 4   V5      40776 non-null  float64
 5   V6      40776 non-null  float64
 6   V7      40776 non-null  float64
 7   V8      40776 non-null  int64
 8   V9      40776 non-null  float64
 9   V10     40776 non-null  float64
 10  V11     40776 non-null  int64
 11  V13     40776 non-null  float64
 12  V19     40776 non-null  int64
 13  V22     40776 non-null  int64
 14  V30     40776 non-null  int64
 15  V33     40776 non-null  int64
 16  V35     40776 non-null  int64
 17  V36     40776 non-null  int64
 18  V40     40776 non-null  float64
 19  V41     40776 non-null  int64
 20  V42     40776 non-null  float64
 21  V43     40776 non-null  float64
 22  V45     40776 non-null  int64
 23  V47     40776 non-null  int64
 24  V50     40776 non-null  float64
 25  V51     40776 non-null  int64
 26  V52     40776 non-null  int64
 27  V59     40776 non-null  float64
 28  V63     40776 non-null  int64
 29  V72     40776 non-null  int64
 30  V75     40776 non-null  int64
 31  class   40776 non-null  int64
dtypes: float64(14), int64(18)
memory usage: 10.0 MB

In [373]:
df['class'].value_counts()

class
1    20439
0    20337
Name: count, dtype: int64

In [375]:
X = df.drop(['class'], axis=1)

y = df['class']

In [377]:
from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [379]:
from sklearn.tree import DecisionTreeClassifier

In [381]:
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=0)



clf_gini.fit(X_train1, y_train1)

DecisionTreeClassifier(max_depth=5, random_state=0)

In [383]:
y_pred_gini = clf_gini.predict(X_test1)
y_pred_gini

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [385]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [387]:
accuracy_score(y_test1,y_pred_gini)

0.6418964107899234

In [389]:
f1_score(y_test1,y_pred_gini)

0.6542297481524

In [405]:
d=pd.read_csv("test.csv")
d

,Index,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V43,V45,V47,V50,V51,V52,V59,V63,V72,V75
0,40977,3.0,97.0,2.0,3,475.0,23.0,11.0,10,146.0,...,123.0,1,8,0.0,0,1,5.0,6,14,0
1,24157,7.0,29.0,11.0,10,8.0,2.0,11.0,16,19.0,...,26.0,1,8,2.0,4,1,45.0,6,2,26
2,56238,2.0,9.0,5.0,1,1003.0,29.0,2.0,29,54.0,...,10.0,1,5,35.0,1,1,6.0,6,2,3
3,55411,0.0,0.0,22.0,17,1527.0,28.0,4.0,24,28.0,...,95.0,8,8,1.0,2,1,15.0,8,1,3
4,53175,13.0,-1.0,46.0,6,4.0,5.0,16.0,15,22.0,...,30.0,5,8,13.0,1,1,5.0,6,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17471,17197,5.0,8.0,2.0,17,1025.0,114.0,5.0,17,49.0,...,1835.0,1,8,0.0,9,0,3.0,6,2,1
17472,14094,1.0,22.0,4.0,10,1.0,7.0,7.0,10,50.0,...,65.0,5,0,0.0,0,0,2.0,2,2,1
17473,34598,2.0,66.0,4.0,6,1025.0,38.0,2.0,38,38.0,...,104.0,1,8,0.0,9,0,1.0,7,1,7
17474,17845,1.0,944.0,6.0,6,1084.0,6.0,14.0,23,68.0,...,2.0,5,8,19.0,10,2,0.0,7,2,0
17475,11574,2.0,100.0,9.0,1,1.0,0.0,2.0,1,1.0,...,2.0,1,10,32.0,3,1,0.0,4,1,2

In [407]:
X_test=d.drop(['Index'],axis=1)

In [409]:
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=0)



clf_gini.fit(X, y)

DecisionTreeClassifier(max_depth=5, random_state=0)

In [411]:
y_test=clf_gini.predict(X_test)
y_test

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [413]:
Index=d['Index']

In [415]:
result = pd.DataFrame({
    'Index': Index,
    'class': y_test
})
result

       Index  class
0      40977      0
1      24157      0
2      56238      1
3      55411      1
4      53175      0
...      ...    ...
17471  17197      1
17472  14094      0
17473  34598      1
17474  17845      0
17475  11574      0

[17476 rows x 2 columns]

In [417]:
result.to_csv("submission.csv", index=False)